name:  test  in PowerShell 
on: push

jobs:
  test-job:
    name: test in pwsh
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: test in pwsh
        shell: pwsh
        run: |
          mvn clean test -Dgroups="login"
