name: test in PowerShell 
on: push

jobs:
  api-test-job:
    name: test in pwsh
    runs-on: ubuntu-latest
  build-with-Maven:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
         java-version: '11'
         distribution: 'temurin'
         cache: maven
      - name: test GET API test in maven 
        run: mvn verify -Dgroups="login"
